//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.BaseCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DetailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("News.BaseCore.Resources.DetailResources", typeof(DetailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi gọi xử lý dữ liệu !.
        /// </summary>
        public static string CallFunctionError {
            get {
                return ResourceManager.GetString("CallFunctionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhân viên.
        /// </summary>
        public static string ChonNhanVien {
            get {
                return ResourceManager.GetString("ChonNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo file excel nhóm thành công !.
        /// </summary>
        public static string CreateExcelFileGroupSuccess {
            get {
                return ResourceManager.GetString("CreateExcelFileGroupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo file Excel thành công !.
        /// </summary>
        public static string CreateExcelFileSuccess {
            get {
                return ResourceManager.GetString("CreateExcelFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn đơn vị.
        /// </summary>
        public static string DonVi {
            get {
                return ResourceManager.GetString("DonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập file DBF:.
        /// </summary>
        public static string FileDbfInBaoNo {
            get {
                return ResourceManager.GetString("FileDbfInBaoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập file Excel:.
        /// </summary>
        public static string FileExcelBaoNo {
            get {
                return ResourceManager.GetString("FileExcelBaoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Cq.
        /// </summary>
        public static string MaCq {
            get {
                return ResourceManager.GetString("MaCq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string NhanVien {
            get {
                return ResourceManager.GetString("NhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Stt {
            get {
                return ResourceManager.GetString("Stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo file excel gộp:.
        /// </summary>
        public static string TaoFileExcelGop {
            get {
                return ResourceManager.GetString("TaoFileExcelGop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string Thang {
            get {
                return ResourceManager.GetString("Thang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền.
        /// </summary>
        public static string Tien {
            get {
                return ResourceManager.GetString("Tien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file thành công.
        /// </summary>
        public static string UploadFileThanhCong {
            get {
                return ResourceManager.GetString("UploadFileThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn file upload !.
        /// </summary>
        public static string VuiLongChonFileUpload {
            get {
                return ResourceManager.GetString("VuiLongChonFileUpload", resourceCulture);
            }
        }
    }
}
