//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.BaseCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("News.BaseCore.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin.
        /// </summary>
        public static string AddOrEdit {
            get {
                return ResourceManager.GetString("AddOrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  và .
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tầng Bussiness.
        /// </summary>
        public static string BussinessError {
            get {
                return ResourceManager.GetString("BussinessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu Hình.
        /// </summary>
        public static string CauHinh {
            get {
                return ResourceManager.GetString("CauHinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay Đổi.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Chọn .
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- .
        /// </summary>
        public static string ChooseEnd {
            get {
                return ResourceManager.GetString("ChooseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- .
        /// </summary>
        public static string ChooseFirst {
            get {
                return ResourceManager.GetString("ChooseFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn dùng.
        /// </summary>
        public static string ChooseToUse {
            get {
                return ResourceManager.GetString("ChooseToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền chức năng chi tiết.
        /// </summary>
        public static string ChucNangChiTietPermit {
            get {
                return ResourceManager.GetString("ChucNangChiTietPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền chức năng.
        /// </summary>
        public static string ChucNangPermit {
            get {
                return ResourceManager.GetString("ChucNangPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển phiếu.
        /// </summary>
        public static string ChuyenPhieu {
            get {
                return ResourceManager.GetString("ChuyenPhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn thực hiện.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa các mục đã chọn.
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Core.
        /// </summary>
        public static string CoreError {
            get {
                return ResourceManager.GetString("CoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới đơn vị.
        /// </summary>
        public static string CreateDonVi {
            get {
                return ResourceManager.GetString("CreateDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công.
        /// </summary>
        public static string CreateSuccessfully {
            get {
                return ResourceManager.GetString("CreateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới người dùng.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hoạt động.
        /// </summary>
        public static string DangHoatDong {
            get {
                return ResourceManager.GetString("DangHoatDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập Hệ Thống.
        /// </summary>
        public static string DangNhapHeThong {
            get {
                return ResourceManager.GetString("DangNhapHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền danh mục.
        /// </summary>
        public static string DanhMucPermit {
            get {
                return ResourceManager.GetString("DanhMucPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string DataInvalid {
            get {
                return ResourceManager.GetString("DataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa đơn vị.
        /// </summary>
        public static string DeleteDonVi {
            get {
                return ResourceManager.GetString("DeleteDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa người dùng.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string DisplayButton {
            get {
                return ResourceManager.GetString("DisplayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền đơn vị.
        /// </summary>
        public static string DonViPermit {
            get {
                return ResourceManager.GetString("DonViPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa đơn vị.
        /// </summary>
        public static string EditDonVi {
            get {
                return ResourceManager.GetString("EditDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật người dùng.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra!.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xuất hiện khi thêm mới.
        /// </summary>
        public static string ErrorOnCreate {
            get {
                return ResourceManager.GetString("ErrorOnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xuất hiện khi xóa.
        /// </summary>
        public static string ErrorOnDelete {
            get {
                return ResourceManager.GetString("ErrorOnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xuất hiện khi cập nhật.
        /// </summary>
        public static string ErrorOnUpdate {
            get {
                return ResourceManager.GetString("ErrorOnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình xử lý.
        /// </summary>
        public static string HasAnError {
            get {
                return ResourceManager.GetString("HasAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có ký tự không nhận dạng được.
        /// </summary>
        public static string HasWordsRegex {
            get {
                return ResourceManager.GetString("HasWordsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        public static string HeThong {
            get {
                return ResourceManager.GetString("HeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string HuyBo {
            get {
                return ResourceManager.GetString("HuyBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Dbf thành công !.
        /// </summary>
        public static string ImportDbfSuccess {
            get {
                return ResourceManager.GetString("ImportDbfSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Excel thành công !.
        /// </summary>
        public static string ImportExcelSuccess {
            get {
                return ResourceManager.GetString("ImportExcelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin {0}.
        /// </summary>
        public static string InformationNotFound {
            get {
                return ResourceManager.GetString("InformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào trống!.
        /// </summary>
        public static string InputModelIsNull {
            get {
                return ResourceManager.GetString("InputModelIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động.
        /// </summary>
        public static string isActive {
            get {
                return ResourceManager.GetString("isActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản người dùng đang bị khóa.
        /// </summary>
        public static string IsLockedUser {
            get {
                return ResourceManager.GetString("IsLockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hoạt động.
        /// </summary>
        public static string isNotActive {
            get {
                return ResourceManager.GetString("isNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa sử dụng.
        /// </summary>
        public static string IsNotUsed {
            get {
                return ResourceManager.GetString("IsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng.
        /// </summary>
        public static string IsUsed {
            get {
                return ResourceManager.GetString("IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        public static string KetThuc {
            get {
                return ResourceManager.GetString("KetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khoá.
        /// </summary>
        public static string KeywordSearch {
            get {
                return ResourceManager.GetString("KeywordSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        public static string Khoa {
            get {
                return ResourceManager.GetString("Khoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa phiếu.
        /// </summary>
        public static string KhoaPhieu {
            get {
                return ResourceManager.GetString("KhoaPhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhận phiếu.
        /// </summary>
        public static string KhongNhanPhieu {
            get {
                return ResourceManager.GetString("KhongNhanPhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết website.
        /// </summary>
        public static string LinkWebsites {
            get {
                return ResourceManager.GetString("LinkWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách loại dịch vụ.
        /// </summary>
        public static string ListLoaiDichVu {
            get {
                return ResourceManager.GetString("ListLoaiDichVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tỉnh thành.
        /// </summary>
        public static string ListProvinces {
            get {
                return ResourceManager.GetString("ListProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền loại dịch vụ.
        /// </summary>
        public static string LoaiDichVuPermit {
            get {
                return ResourceManager.GetString("LoaiDichVuPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đăng nhập.
        /// </summary>
        public static string LoginRequire {
            get {
                return ResourceManager.GetString("LoginRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã / Tên.
        /// </summary>
        public static string MA_TEN {
            get {
                return ResourceManager.GetString("MA_TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu.
        /// </summary>
        public static string MatKhau {
            get {
                return ResourceManager.GetString("MatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền menu.
        /// </summary>
        public static string MenuPermit {
            get {
                return ResourceManager.GetString("MenuPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm nâng cao.
        /// </summary>
        public static string NangCao {
            get {
                return ResourceManager.GetString("NangCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp theo.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền nghiệp vụ.
        /// </summary>
        public static string NghiepVuPermit {
            get {
                return ResourceManager.GetString("NghiepVuPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền người dùng.
        /// </summary>
        public static string NguoiDungPermit {
            get {
                return ResourceManager.GetString("NguoiDungPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận báo hỏng.
        /// </summary>
        public static string NhanBaoHong {
            get {
                return ResourceManager.GetString("NhanBaoHong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận phiếu.
        /// </summary>
        public static string NhanPhieu {
            get {
                return ResourceManager.GetString("NhanPhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn.
        /// </summary>
        public static string NoSelectedItemsToDeleteMessage {
            get {
                return ResourceManager.GetString("NoSelectedItemsToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chú Thích.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hoặc .
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        public static string PasswordRequire {
            get {
                return ResourceManager.GetString("PasswordRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết chương trình.
        /// </summary>
        public static string QuickSelectSystem {
            get {
                return ResourceManager.GetString("QuickSelectSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc thêm....
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tầng Repository.
        /// </summary>
        public static string RepositoryError {
            get {
                return ResourceManager.GetString("RepositoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        public static string RoleSetting {
            get {
                return ResourceManager.GetString("RoleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu gọn.
        /// </summary>
        public static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cần gửi không được để trống.
        /// </summary>
        public static string SmsDanhSachNguoiNhanEmpty {
            get {
                return ResourceManager.GetString("SmsDanhSachNguoiNhanEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi tin nhắn không thành công.
        /// </summary>
        public static string SmsGuiTinNhanKhongThanhCong {
            get {
                return ResourceManager.GetString("SmsGuiTinNhanKhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi tin nhắn thành công.
        /// </summary>
        public static string SmsGuiTinNhanThanhCong {
            get {
                return ResourceManager.GetString("SmsGuiTinNhanThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung tin nhắn không được để trống.
        /// </summary>
        public static string SmsNoiDungEmpty {
            get {
                return ResourceManager.GetString("SmsNoiDungEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi đồng bộ dữ liệu.
        /// </summary>
        public static string SyncError {
            get {
                return ResourceManager.GetString("SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Đăng Nhập.
        /// </summary>
        public static string TenDangNhap {
            get {
                return ResourceManager.GetString("TenDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhà trạm.
        /// </summary>
        public static string ThongTinNhaTram {
            get {
                return ResourceManager.GetString("ThongTinNhaTram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền tỉnh thành.
        /// </summary>
        public static string TinhThanhPermit {
            get {
                return ResourceManager.GetString("TinhThanhPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số bản ghi.
        /// </summary>
        public static string TotalRecord {
            get {
                return ResourceManager.GetString("TotalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string TuKhoaTimKiem {
            get {
                return ResourceManager.GetString("TuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật từ PTTB.
        /// </summary>
        public static string UpdatePTTBButton {
            get {
                return ResourceManager.GetString("UpdatePTTBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string UpdateSuccessfully {
            get {
                return ResourceManager.GetString("UpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng cần cập nhật không tồn tại.
        /// </summary>
        public static string UpdatingItemsNotExists {
            get {
                return ResourceManager.GetString("UpdatingItemsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được để trống.
        /// </summary>
        public static string UserNameRequire {
            get {
                return ResourceManager.GetString("UserNameRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền.
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền vệ tinh.
        /// </summary>
        public static string VeTinhPermit {
            get {
                return ResourceManager.GetString("VeTinhPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tầng WebApplication.
        /// </summary>
        public static string WebApplicationError {
            get {
                return ResourceManager.GetString("WebApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webservice hiện tại không lấy được dữ liệu(Timeout).
        /// </summary>
        public static string WebServiceTimeout {
            get {
                return ResourceManager.GetString("WebServiceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai password.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa cảnh báo.
        /// </summary>
        public static string XoaCanhBaoBts {
            get {
                return ResourceManager.GetString("XoaCanhBaoBts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất phiếu.
        /// </summary>
        public static string XuatPhieu {
            get {
                return ResourceManager.GetString("XuatPhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
